name: Run Sancus examples
on:
  push:
  pull_request:
  # trigger a cron job every monday at 8am
  schedule:
    - cron: '00 08 * * MON'

jobs:
  test-examples:
    name: Test of ${{ matrix.example }} example
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-${{ matrix.sancus-security }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - example: hello-world
            flags: 
            sancus-security: 64
          - example: hello-world
            flags: 
            sancus-security: 128
          - example: hello-library
            flags: ARCHIVE_MODE=thick 
            sancus-security: 64
          - example: hello-library
            flags: ARCHIVE_MODE=thin
            sancus-security: 64
          - example: sensor-reader
            flags: 
            sancus-security: 64
          - example: sensor-reader
            flags: 
            sancus-security: 128
          - example: arithmetic
            flags: 
            sancus-security: 64
          - example: fileio
            flags: 
            sancus-security: 64
          - example: timer
            flags: 
            sancus-security: 64
          - example: violation
            flags: 
            sancus-security: 64
          - example: sancus-step
            flags: 
            sancus-security: 64
          - example: dma
            flags: 
            sancus-security: 64

    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: make SANCUS_SECURITY=${{ matrix.sancus-security }} CI=1 ${{ matrix.flags }} ${{ matrix.example }}.sim
        name: Build and run ${{ matrix.example }} @ ${{ matrix.sancus-security}} bit security
