name: Run Sancus examples
on:
  # only run on master cause we'll push a Docker image
  push: 
    branches:
      - master
  # trigger a cron job every monday at 8am
  schedule:
    - cron: '00 08 * * MON'

jobs:
  build-docker:
    name: Build and push Docker image sancus-devel-${{ matrix.sancus-security }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sancus-security: [64, 128]
    steps:
      - name: Check out sancus-main
        uses: actions/checkout@v2
        with:
            repository: sancus-tee/sancus-main
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          cd sancus-main/docker && make build SANCUS_SECURITY=${{ matrix.sancus-security }} 
          docker images
          docker tag sancus-devel ${{ secrets.DOCKER_USERNAME }}/sancus-devel-${{ matrix.sancus-security }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/sancus-devel-${{ matrix.sancus-security }} 
    
  test-examples:
    name: Test ${{ matrix.example }} @ ${{ matrix.sancus-security}} bit security
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-${{ matrix.sancus-security }}:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    strategy:
      matrix:
        example: [hello-world, sensor-reader, arithmetic, fileio, timer, violation, sancus-step, dma]
        sancus-security: [64, 128]
        include:
          - example: hello-library
            flags: ARCHIVE_MODE=thick 
            sancus-security: 64
          - example: hello-library
            flags: ARCHIVE_MODE=thin
            sancus-security: 64

    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: make SANCUS_SECURITY=${{ matrix.sancus-security }} CI=1 ${{ matrix.flags }} ${{ matrix.example }}.sim
        name: Build and run ${{ matrix.example }} @ ${{ matrix.sancus-security}} bit security
