# This is the ci workflow to run after the docker push

name: Run Sancus examples

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # Run on pull requests (automatically uses PR in docker name)
  pull_request:
  # Also run on a schedule (once a month)
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  test-examples:
    name: Test of ${{ matrix.example }} example
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - example: hello-world
            flags: 
          - example: hello-library
            flags: ARCHIVE_MODE=thick 
          - example: hello-library
            flags: ARCHIVE_MODE=thin
          - example: sensor-reader
            flags: 
          - example: arithmetic
            flags: 
          - example: fileio
            flags: 
          - example: timer
            flags: 
          - example: violation
            flags: 
          - example: sancus-step
            flags: 
          - example: dma
            flags: 

    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: make SANCUS_SECURITY=64 CI=1 ${{ matrix.flags }} ${{ matrix.example }}.sim
        name: Build and run ${{ matrix.example }}

  test-64-bit:
    name: Test of 128 bit security
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-128:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    steps:
      - uses: actions/checkout@v2
        name: Pull repository
      - run: make SANCUS_SECURITY=128 CI=1 hello-world.sim
        name: Build and run hello world @ 128 bit security
