# This is the ci workflow to run after the docker push

name: Run Sancus examples

on:
  # Run on pushes to master
  push:
    branches:
      - master
  # Run on pull requests (automatically uses PR in docker name)
  pull_request:
  # Also run on a schedule (once a month)
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  test-examples:
    name: Test of all examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - example: hello-world
            flags: 
          - example: hello-library
            flags: ARCHIVE_MODE=thick 
          - example: hello-library
            flags: ARCHIVE_MODE=thin
          - example: sensor-reader
            flags: 
          - example: arithmetic
            flags: 
          - example: fileio
            flags: 
          - example: timer
            flags: 
          - example: violation
            flags: 
          - example: sancus-step
            flags: 
          - example: dma
            flags: 

    steps:
      # Log in to gh pkg for docker
      - name: Log into Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      # Check out repo (with PR). Will be mounted in Docker under /github/workflows
      - name: Check out repository
        uses: actions/checkout@v2
      
      # Run example in Docker
      - name: Run 64-bit ${{ matrix.example }} example in Docker	    
        uses: docker://docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-64:merge
        with:
          entrypoint: /bin/bash
          args: -c "cd /github/workspace/ && make SANCUS_SECURITY=64 CI=1 ${{ matrix.flags }} ${{ matrix.example }}.sim"

  test-64-bit:
    name: Test of 128 bit security
    runs-on: ubuntu-latest

    steps:
      # Log in to gh pkg for docker
      - name: Log into Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      # Check out repo (with PR). Will be mounted in Docker under /github/workflows
      - name: Check out repository
        uses: actions/checkout@v2
      
      # Run example in Docker but choose 128 bit and hello world example here
      # Unfortunately, the uses parameter can not be modified via a matrix, 
      #   and placing security in the matrix does not work.
      - name: Run {{ matrix.security }}-bit example in Docker	    
        uses: docker://docker.pkg.github.com/sancus-tee/sancus-main/sancus-devel-128:merge
        with:
          entrypoint: /bin/bash
          args: -c "cd /github/workspace/ && make SANCUS_SECURITY=128 CI=1 hello-world.sim"
